### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by hungdopamineapp** [Emurgo/csl-mobile-bridge#103]
I got the issue when run on ios from xcode
![Screenshot 2023-08-01 at 16 27 59](https://github.com/Emurgo/csl-mobile-bridge/assets/92638814/61e3110f-a725-4712-be41-cb4d5530d737)

My step when install the lib:

1. `yarn add @emurgo/csl-mobile-bridge`
2. `cd ios && npx pod-install`
3. Open Xcode and run

I tried some solution from community but still not work:
 - change `source="$(readlink "${source}")"` -> `source="$(readlink -f"${source}")"`
 - Tick on `Build Phrases`/`[CP]Embed Pods Frameworks`/`For install builds only`
 
 System:
  "react-native": "0.71.3",
  "@emurgo/csl-mobile-bridge": "^5.1.2",
  
  Macos: Ventura - Version 13.3.1 (a) (22E772610a)
  Xcode: Version 14.3 (14E222b)
    
  Please give me some idea to resolve this problem. Thanks your work a lot!

**Comment by lisicky** [comment]
Hi @hungdopamineapp ! Which rust version do you use ?

**Comment by lisicky** [comment]
I close it, because didn't get response
