### ISSUE TITLE
Build failed in Xcode : error[E0308]: mismatched types

### ISSUE THREAD

**Issue by divyangkhatri** [Emurgo/csl-mobile-bridge#107]
Versions

"react-native": "^0.72.7",
"@emurgo/csl-mobile-bridge": "^5.1.3",
Xcode: 15.2
rust: cargo 1.79.0

<img width="1496" alt="Screenshot 2024-06-26 at 6 19 27 PM" src="https://github.com/Emurgo/csl-mobile-bridge/assets/59201976/a4e1ea5b-5069-46ac-bba8-e7afaf437bf5">

**Comment by lisicky** [comment]
Hey @divyangkhatri ! Could you try rust 1.70 or 1.73 ?

**Comment by divyangkhatri** [comment]
@lisicky Thank you for the solution.
It is working for iOS with rust version 1.70.0
But in android it throwing the error

`error: cannot find macro 'debug_assert' in this scope`

<img width="1496" alt="Screenshot 2024-06-28 at 1 01 54 PM" src="https://github.com/Emurgo/csl-mobile-bridge/assets/59201976/a13db9ac-bfa4-4232-8a2e-9dd4adb35b89">

**Comment by lisicky** [comment]
@divyangkhatri  my current configuration, let me know if it won't work 

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
aarch64-apple-ios-sim
aarch64-linux-android
armv7-linux-androideabi
i686-linux-android
wasm32-unknown-unknown
x86_64-apple-ios
x86_64-linux-android

active toolchain
----------------

1.74-aarch64-apple-darwin (default)
rustc 1.74.1 (a28077b28 2023-12-04)

**Comment by lisicky** [comment]
Hey @divyangkhatri , could you tell me if it helped ?

**Comment by lisicky** [comment]
Close, since have no answer
