### ISSUE TITLE
Problem with implementation: [TypeError: Cannot read property 'bip32PrivateKeyFromBip39Entropy' of null]

### ISSUE THREAD

**Issue by Working-Ejp** [Emurgo/csl-mobile-bridge#108]
Hello,

We've stumbled on very first obstacle, setup is as follows:

    "@emurgo/csl-mobile-bridge": "^5.1.3" or "@emurgo/react-native-haskell-shelley": "^5.0.0"
    "react": "18.2.0",
    "react-native": "0.71.19" -> because we've seen that library shows "react-native":">=0.67.5 <0.72.0"

After initial installation, when we try to access any class it returns null. I guess Haskel Shelley is not properly initiated. We've tried linking it manually, as `react-native link` command is no longer possible since RN 0.60.0, but with no success.

After we manually link `@emurgo/react-native-haskell-shelley`, error msg remains, e.g [TypeError: Cannot read property 'bip32PrivateKeyFromBip39Entropy' of null]

If we go with `@emurgo/csl-mobile-bridge`, after manual link, it requires `react-native-haskell-shelley.h`.

Any suggestion is very much appreciated.

Regards.

**Comment by lisicky** [comment]
Hi @Working-Ejp !
Did you tried it on android or iOS ? 
Also [Yoroi](https://github.com/Emurgo/yoroi) is using csl-mobile-bridge, you can use it as an example. For android I would also check gradle files ( you can compare it with Yoroi's one )

**Comment by Working-Ejp** [comment]
Hi, we made it work, it was mostly related to problems with rust and ndk needed to be installed through cargo

**Comment by lisicky** [comment]
Could you write which steps did you performed ? It might be helpful for troubleshooting if someone will meet a similar problem
