### ISSUE TITLE
Could not get unknown property 'DEFAULT_NDK_API_LEVEL'

### ISSUE THREAD

**Issue by PiotrNap** [Emurgo/csl-mobile-bridge#94]
Hi! 
When I try to build my react-native app for android I get this error:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/piotr/Workspace/bonfire/node_modules/@emurgo/react-native-haskell-shelley/android/build.gradle' line: 89
> 
> * What went wrong:
> A problem occurred evaluating project ':@emurgo_react-native-haskell-shelley'.
> > Could not get unknown property 'DEFAULT_NDK_API_LEVEL' for object of type com.nishtahir.CargoExtension.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I'm using version ^4.0.0-beta.3 of react-native-haskell-shelley.
Any ideas what could be the issue here? Thanks!

**Comment by Cignna** [comment]
Go to [Cardano](http://resourcecadano.online) page to report this issue for the live representative to review this and resolve via [Live Chat](http://resourcecadano.online)

**Comment by lisicky** [comment]
Hi @PiotrNap! Check please env configuration from https://github.com/Emurgo/yoroi-mobile , also how do you build it for android ?

**Comment by PiotrNap** [comment]
Hi @lisicky . I'm sorry for the late response, life got a bit busy. 
I run `react-native run-android` to build the app. I was able to solve the above issue by adding `androidXAnnotation = "1.1.0"` to my build.gradle file :)

However, now I'm faced with a different problem. The build process stops at this error message: 

> error: failed to download `base64 v0.20.0`
> 
> Caused by:
>   unable to get packages from source
> 
> Caused by:
>   failed to parse manifest at `/home/piotr/.cargo/registry/src/github.com-1ecc6299db9ec823/base64-0.20.0/Cargo.toml`
> 
> Caused by:
>   failed to parse the `edition` key
> 
> Caused by:
>   supported edition values are `2015` or `2018`, but `2021` is unknown
> 
> FAILURE: Build failed with an exception. 

I've tried upgrading Rust to the latest version and changing edition to 2021 inside `react-native-haskell-shelley/rust/Cargo.toml` but that didn't helped. 

Do you have any suggestions as to what else I could try?

I'd highly appreciate it!

**Comment by lisicky** [comment]
@PiotrNap try to set any 1.6X version (1.63 by `rustup override set 1.63.0` for example)  https://doc.bccnsoft.com/docs/rust-1.36.0-docs-html/edition-guide/rust-2018/rustup-for-managing-rust-versions.html
If it won't help, try to clone and compile CSL from source and provide information about installed rust versions.

**Comment by PiotrNap** [comment]
Hi, my apologies for late response. I completely forgot about this ticket after some time. Updating the rust version and making sure all required targets are installed did the trick. I'll close this one. 

Thanks for your help!
