### ISSUE TITLE
build error Mac OS for Simulator

### ISSUE THREAD

**Issue by dynamicstrategies** [Emurgo/csl-mobile-bridge#98]
Can you please check if the issue from https://github.com/Emurgo/csl-mobile-bridge/issues/81 has been addressed?

After npm installing the new package and building it for a Simulator on Mac OS I get the same error

![image](https://user-images.githubusercontent.com/75221952/224855500-29eeffa6-7eb7-443a-9c83-d7e24097b666.png)

The workaround for the error, is to comment out the line with "Mac.OSX.sdk" from the `build.sh` file. After that, it compiles successfully for a simulator

Compiling for release doesn't require a workaround, and works as intended out of the box. Therefore the issue seems to be related to just the simulator target

All the best

**Comment by lisicky** [comment]
Hi @dynamicstrategies ! Could you provide more information about your environment (macOS, Xcode version and etc.) ? We need it to localize the problem.

**Comment by dynamicstrategies** [comment]
Hi,

The build was run on a virtualized Mac environment: https://github.com/kholia/OSX-KVM

The build fails only for the Simulator x86 in XCode

The build for arm64 to go onto the Apple store builds correctly, so the real issue is not being able to run it on a simulator in that environment

Xcode version: 14.1 (14B47b)
SDK iOS: 16.1
Rustup version: 1.25.1
Rustc version: 1.65.0

Trying to compile: @emurgo/react-native-haskell-shelley": "^5.0.0"

Thanks

**Comment by lisicky** [comment]
Hi @dynamicstrategies ! We have updated build script in the last version, could you try it https://www.npmjs.com/package/@emurgo/csl-mobile-bridge
